Get Block Children
jakeswenson/notion pull request #4
Opened 2021-05-16 06:58 UTC by bspradling

## Description 

`TODO`

2021-05-16 15:28 UTC, jakeswenson requested changes

2021-05-16 15:28 UTC, jakeswenson commented on src/models.rs
> +    r#type: BlockType,
Neat, but instead what about 
```suggestion
    #[serde(rename = "type")]
    block_type: BlockType,
```

2021-05-16 15:28 UTC, jakeswenson commented on src/models.rs
> +    r#type: BlockType,
Should block actually be an `enum`?
```rust
pub enum Block {
    Paragraph {
       #[serde(flatten)]
       common: BlockCommon
    }
    ...
```

2021-05-16 16:35 UTC, bspradling commented on src/models.rs
> +    r#type: BlockType,
Yeah it needs to be. ill refactor it

2021-05-17 06:12 UTC, bspradling commented
Closing in favor of #9

2021-05-17 06:12 UTC, closed without merging