Change text to rich_text
jakeswenson/notion pull request #44
Opened 2022-11-01 20:02 UTC by ahmetrehaseker

Notion API expects `rich_text` instead of `text` while querying the database with property filtering

2022-11-13 05:28 UTC, jakeswenson requested changes
Thanks for the PR! I appreciate it. I think the build is failing due to a cargo fmt issue, do you know if you're seeing that on your end?

I left a comment to add a doc comment for the private method we'd be making public in this PR.

Thanks again!

2022-11-13 05:28 UTC, jakeswenson commented on src/lib.rs
> +    pub async fn make_json_request(&self, request: RequestBuilder) -> Result<Object, Error> {
If we make this public can we add some doc comments on it?

2022-11-19 16:41 UTC, jakeswenson approved these changes
This is awesome! Thank you for all the improvements! If you don't want to add the doc comment I can before releasing? Let me know how you'd like to proceed!

2022-11-19 16:41 UTC, jakeswenson commented on src/lib.rs
> +    pub async fn create_page<T: Into<PageCreateRequest>>(&self, page: T) -> Result<Page, Error> {
Can we add a doc document to this?

```suggestion
    /// Creates a new page
    pub async fn create_page<T: Into<PageCreateRequest>>(&self, page: T) -> Result<Page, Error> {
```

2022-11-19 16:43 UTC, ahmetrehaseker commented
Sorry, I should add WIP tag I guess, I am testing this now when I finalize the tests I will add the documentation

2022-11-20 17:35 UTC, ahmetrehaseker commented
I am unable to remove that WIP tag, I tested the changes the PR is ready to be merged I guess.

2023-01-01 05:08 UTC, AusCyberman commented
Can you yknow merge this?

2023-01-02 07:55 UTC, jakeswenson approved these changes
LGTM! Thank you for the contribution!

2023-01-02 16:19 UTC, merged